### ISSUE TITLE
Type error: "liquiditions" table

### ISSUE THREAD

**Issue by Moicky** [crypto-lake/lake-api#13]
* Lake API version: latest
* Python version: 3.12
* Operating System: macOS

### Description

The type for the list of tables is incorrect in the page. Using that type would result in the query failing, specifying the correct one results in a Pylance error 😄 

**Please only report bugs in the code of this library in Github issues here. All other questions (or if you're unsure) should be directed to our support on hi (at) crypto-lake (dot) com.**

### What happened

```
session = Session(
    aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    region_name="us-west-1",
)

liqs = load_data(
    "liquiditions",
    symbols=["BTC-USDT-PERP"],
    exchanges=["BINANCE_FUTURES"],
    start=datetime.fromisoformat("2024-12-01T00:00:00Z"),
    end=datetime.fromisoformat("2024-12-14T00:00:00Z"),
    boto3_session=session,
)

Don't share your access keys!
```

**Comment by leftys** [comment]
hi, thanks for the fix PR, will release probably tomorrow

**Comment by leftys** [comment]
fix released, closing
