### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by IngLP** [crypto-lake/lake-api#5]
* Lake API version: 0.8.0
* Python version: 3.10
* Operating System: macOS

### Description

I want to report corrupted trades for all symbols on Coinbase, at 2023-03-04.

### What I Did

I tried to download the aforementioned data. Returned DataFrame is empty and the following log is printed.
```
WARNING  [_read_parquet.py:59] Ignoring corrupted file = s3://qnt.data/market-data/cryptofeed/trades/exchange=COINBASE/symbol=ADA-USD/dt=2023-03-04/1.snappy.parquet
```

**Comment by leftys** [comment]
closing an old issue resolved iirc by email
