### ISSUE TITLE
At what time of the day is the data from previous day available?

### ISSUE THREAD

**Issue by xmariachi** [crypto-lake/lake-api#8]
Question:
I would like to know:
* How many times per day is data consolidated to be available? (i.e. once a day, once per hour ...)
* At which hour in the day data is expected to be finished?

Use case is to read new data coming in, scheduling data ingestion from last day/hour at a certain time.
I checked the docs, and didn't find this.

Thanks

**Comment by leftys** [comment]
Hi, data are being uploaded to the storage once a day between 01:00 AM UTC and 3:15 AM UTC.

(Btw ideally use our support email for questions in the future please. We would like to reserve github issues for bugs and you will get faster response on the email.)
